<?php
// @codingStandardsIgnoreFile
/**
 * Generated frontend static JavaScript data map for s2Member Pro.
 *
 * Generated: 2026-09-06 22:43 UTC (260906.2243)
 *
 * Generated from paired data-boundary markers in the canonical frontend JavaScript source files.
 * Do not edit this file by hand; the project build regenerates it from the canonical JavaScript source.
 *
 * @package s2Member\CSS_JS
 * @since 260906.0738
 */
if(!defined('ABSPATH'))
	exit;

$vars = array(
	'u' => $GLOBALS['WS_PLUGIN__']['s2member_pro']['c']['dir_url'],
	'i' => $GLOBALS['WS_PLUGIN__']['s2member_pro']['c']['dir_url'].'/src/images',
);

//260906.1530 Evaluate all values by default; an optional key set can restrict evaluation to selected stable slots.
$s2_data_keys = (isset($s2_data_keys) && is_array($s2_data_keys)) ? $s2_data_keys : NULL;
$data = array();

if($s2_data_keys === NULL || isset($s2_data_keys[0]))
	$data[0] = /*d*/ $vars["i"] /*b*/;
if($s2_data_keys === NULL || isset($s2_data_keys[1]))
	$data[1] = /*d*/ _x("— Oops, you missed something: —", "s2member-front", "s2member") /*b*/;
if($s2_data_keys === NULL || isset($s2_data_keys[2]))
	$data[2] = /*d*/ _x("Security Verification missing. Please try again.", "s2member-front", "s2member") /*b*/;
if($s2_data_keys === NULL || isset($s2_data_keys[3]))
	$data[3] = /*d*/ _x ("Please choose a Billing Method.", "s2member-front", "s2member") /*b*/;
if($s2_data_keys === NULL || isset($s2_data_keys[4]))
	$data[4] = /*d*/ _x("Passwords do not match up. Please try again.", "s2member-front", "s2member") /*b*/;
if($s2_data_keys === NULL || isset($s2_data_keys[5]))
	$data[5] = /*d*/ sprintf(_x("Password MUST be at least %s characters. Please try again.", "s2member-front", "s2member"), c_ws_plugin__s2member_user_securities::min_password_length()) /*b*/;
if($s2_data_keys === NULL || isset($s2_data_keys[6]))
	$data[6] = /*d*/ sprintf(_x("Password strength MUST be %s. Please try again.", "s2member-front", "s2member"), c_ws_plugin__s2member_user_securities::min_password_strength_label()) /*b*/;
if($s2_data_keys === NULL || isset($s2_data_keys[7]))
	$data[7] = /*d*/ esc_html (_x ("Submit Form", "s2member-front", "s2member")) /*b*/;
if($s2_data_keys === NULL || isset($s2_data_keys[8]))
	$data[8] = /*d*/ esc_attr (_x ("en_US", "s2member-front paypal-button-lang-code", "s2member")) /*b*/;
if($s2_data_keys === NULL || isset($s2_data_keys[9]))
	$data[9] = /*d*/ esc_attr (_x ("Submit Form", "s2member-front", "s2member")) /*b*/;
if($s2_data_keys === NULL || isset($s2_data_keys[10]))
	$data[10] = /*d*/ esc_attr (_x ("Calculating Sales Tax...", "s2member-front", "s2member")) /*b*/;
if($s2_data_keys === NULL || isset($s2_data_keys[11]))
	$data[11] = /*d*/ _x("calculating sales tax...", "s2member-front", "s2member") /*b*/;
if($s2_data_keys === NULL || isset($s2_data_keys[12]))
	$data[12] = /*d*/ admin_url("/admin-ajax.php") /*b*/;
if($s2_data_keys === NULL || isset($s2_data_keys[13]))
	$data[13] = /*d*/ c_ws_plugin__s2member_utils_encryption::encrypt ("ws-plugin--s2member-pro-paypal-ajax-tax") /*b*/;
if($s2_data_keys === NULL || isset($s2_data_keys[14]))
	$data[14] = /*d*/ _x("<strong>Sales Tax%s:</strong> %s<br /><strong>— Total%s:</strong> %s", "s2member-front", "s2member") /*b*/;
if($s2_data_keys === NULL || isset($s2_data_keys[15]))
	$data[15] = /*d*/ _x("Today", "s2member-front", "s2member") /*b*/;
if($s2_data_keys === NULL || isset($s2_data_keys[16]))
	$data[16] = /*d*/ _x("Create Profile", "s2member-front", "s2member") /*b*/;
if($s2_data_keys === NULL || isset($s2_data_keys[17]))
	$data[17] = /*d*/ _x("Your Profile", "s2member-front", "s2member") /*b*/;
if($s2_data_keys === NULL || isset($s2_data_keys[18]))
	$data[18] = /*d*/ $GLOBALS["WS_PLUGIN__"]["s2member"]["o"]["pro_stripe_api_image"] /*b*/;
if($s2_data_keys === NULL || isset($s2_data_keys[19]))
	$data[19] = /*d*/ $GLOBALS["WS_PLUGIN__"]["s2member"]["o"]["pro_stripe_api_publishable_key"] /*b*/;
if($s2_data_keys === NULL || isset($s2_data_keys[20]))
	$data[20] = /*d*/ $GLOBALS["WS_PLUGIN__"]["s2member"]["o"]["pro_stripe_api_allow_remember_me"] /*b*/;
if($s2_data_keys === NULL || isset($s2_data_keys[21]))
	$data[21] = /*d*/ _x("Add", "s2member-front", "s2member") /*b*/;
if($s2_data_keys === NULL || isset($s2_data_keys[22]))
	$data[22] = /*d*/ _x("No Billing Method; please try again.", "s2member-front", "s2member") /*b*/;
if($s2_data_keys === NULL || isset($s2_data_keys[23]))
	$data[23] = /*d*/ c_ws_plugin__s2member_utils_encryption::encrypt("ws-plugin--s2member-pro-stripe-ajax-tax") /*b*/;
if($s2_data_keys === NULL || isset($s2_data_keys[24]))
	$data[24] = /*d*/ c_ws_plugin__s2member_utils_encryption::encrypt ("ws-plugin--s2member-pro-authnet-ajax-tax") /*b*/;

return $data;
